//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandasApp.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.22gc.com.br")]
        public string DB_HOST
        {
            get
            {
                return ((string)(this["DB_HOST"]));
            }
            set
            {
                this["DB_HOST"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string DB_PORT
        {
            get
            {
                return ((string)(this["DB_PORT"]));
            }
            set
            {
                this["DB_PORT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22gc_demandas1746")]
        public string DB_NAME
        {
            get
            {
                return ((string)(this["DB_NAME"]));
            }
            set
            {
                this["DB_NAME"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22gc_mysql")]
        public string DB_USER
        {
            get
            {
                return ((string)(this["DB_USER"]));
            }
            set
            {
                this["DB_USER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wxOoZLex1ary6SX5")]
        public string DB_PASS
        {
            get
            {
                return ((string)(this["DB_PASS"]));
            }
            set
            {
                this["DB_PASS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dados1746")]
        public string TABLE_NAME
        {
            get
            {
                return ((string)(this["TABLE_NAME"]));
            }
            set
            {
                this["TABLE_NAME"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AUTH_COOKIE
        {
            get
            {
                return ((string)(this["AUTH_COOKIE"]));
            }
            set
            {
                this["AUTH_COOKIE"] = value;
            }
        }
    }
}